name: ItemRenamer
version: 1.0
main: com.gmail.thegurugamers.Main
description: Item Stuff!
author: TheGamingGrunts
website: www.youtube.com/TheGamingGrunts
commands:
  rename:
    description: Rename your item!
    permission: renamer.rename